# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/danilo/Trabalho1_EDA/Cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/danilo/Trabalho1_EDA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danilo/Trabalho1_EDA/CMakeFiles /home/danilo/Trabalho1_EDA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danilo/Trabalho1_EDA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Cpp

# Build rule for target.
Cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Cpp
.PHONY : Cpp

# fast build rule for target.
Cpp/fast:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/build
.PHONY : Cpp/fast

AbstractHashTable.o: AbstractHashTable.cpp.o
.PHONY : AbstractHashTable.o

# target to build an object file
AbstractHashTable.cpp.o:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/AbstractHashTable.cpp.o
.PHONY : AbstractHashTable.cpp.o

AbstractHashTable.i: AbstractHashTable.cpp.i
.PHONY : AbstractHashTable.i

# target to preprocess a source file
AbstractHashTable.cpp.i:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/AbstractHashTable.cpp.i
.PHONY : AbstractHashTable.cpp.i

AbstractHashTable.s: AbstractHashTable.cpp.s
.PHONY : AbstractHashTable.s

# target to generate assembly for a file
AbstractHashTable.cpp.s:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/AbstractHashTable.cpp.s
.PHONY : AbstractHashTable.cpp.s

BinaryTreeUnbalanced.o: BinaryTreeUnbalanced.cpp.o
.PHONY : BinaryTreeUnbalanced.o

# target to build an object file
BinaryTreeUnbalanced.cpp.o:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/BinaryTreeUnbalanced.cpp.o
.PHONY : BinaryTreeUnbalanced.cpp.o

BinaryTreeUnbalanced.i: BinaryTreeUnbalanced.cpp.i
.PHONY : BinaryTreeUnbalanced.i

# target to preprocess a source file
BinaryTreeUnbalanced.cpp.i:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/BinaryTreeUnbalanced.cpp.i
.PHONY : BinaryTreeUnbalanced.cpp.i

BinaryTreeUnbalanced.s: BinaryTreeUnbalanced.cpp.s
.PHONY : BinaryTreeUnbalanced.s

# target to generate assembly for a file
BinaryTreeUnbalanced.cpp.s:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/BinaryTreeUnbalanced.cpp.s
.PHONY : BinaryTreeUnbalanced.cpp.s

CPUTimer.o: CPUTimer.cpp.o
.PHONY : CPUTimer.o

# target to build an object file
CPUTimer.cpp.o:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/CPUTimer.cpp.o
.PHONY : CPUTimer.cpp.o

CPUTimer.i: CPUTimer.cpp.i
.PHONY : CPUTimer.i

# target to preprocess a source file
CPUTimer.cpp.i:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/CPUTimer.cpp.i
.PHONY : CPUTimer.cpp.i

CPUTimer.s: CPUTimer.cpp.s
.PHONY : CPUTimer.s

# target to generate assembly for a file
CPUTimer.cpp.s:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/CPUTimer.cpp.s
.PHONY : CPUTimer.cpp.s

LinkedList.o: LinkedList.cpp.o
.PHONY : LinkedList.o

# target to build an object file
LinkedList.cpp.o:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/LinkedList.cpp.o
.PHONY : LinkedList.cpp.o

LinkedList.i: LinkedList.cpp.i
.PHONY : LinkedList.i

# target to preprocess a source file
LinkedList.cpp.i:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/LinkedList.cpp.i
.PHONY : LinkedList.cpp.i

LinkedList.s: LinkedList.cpp.s
.PHONY : LinkedList.s

# target to generate assembly for a file
LinkedList.cpp.s:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/LinkedList.cpp.s
.PHONY : LinkedList.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Cpp.dir/build.make CMakeFiles/Cpp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Cpp"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AbstractHashTable.o"
	@echo "... AbstractHashTable.i"
	@echo "... AbstractHashTable.s"
	@echo "... BinaryTreeUnbalanced.o"
	@echo "... BinaryTreeUnbalanced.i"
	@echo "... BinaryTreeUnbalanced.s"
	@echo "... CPUTimer.o"
	@echo "... CPUTimer.i"
	@echo "... CPUTimer.s"
	@echo "... LinkedList.o"
	@echo "... LinkedList.i"
	@echo "... LinkedList.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

